# Generated by Django 3.1.7 on 2021-03-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', verbose_name='Created Date')),
            ],
            options={
                'db_table': 'APPBASEMODEL',
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appconfig.basemodel')),
                ('name', models.CharField(db_column='DOMAIN', max_length=100, unique=True)),
                ('point', models.FloatField(db_column='POINT', default=0.0, help_text='Set your domain point of your variable', max_length=100)),
            ],
            options={
                'db_table': 'DOMAINS',
            },
            bases=('appconfig.basemodel',),
        ),
        migrations.CreateModel(
            name='KonkordatoList',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appconfig.basemodel')),
                ('borc_sahibi', models.CharField(db_column='DEPT_TITLE', help_text='Borçlunun Adı Soyadı', max_length=150, null=True)),
            ],
            options={
                'db_table': 'KONKORDATO_LIST',
            },
            bases=('appconfig.basemodel',),
        ),
        migrations.CreateModel(
            name='SGKBorcuListesi',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appconfig.basemodel')),
                ('borc_sahibi', models.CharField(db_column='DEPT_TITLE', help_text='Borçlunun Adı Soyadı', max_length=150, null=True)),
                ('kimlikno', models.CharField(db_column='TAXPAYER_NUMBER', help_text='Sahis firmasi ise TCKNO, Tuzel Kisilik iseVergi No', max_length=15)),
                ('borc_miktari', models.FloatField(db_column='DEPT_AMOUNT', help_text='Borç Miktarı')),
            ],
            options={
                'db_table': 'SGK_DEBTS',
            },
            bases=('appconfig.basemodel',),
        ),
        migrations.CreateModel(
            name='SystemBlackList',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appconfig.basemodel')),
                ('borc_sahibi', models.CharField(db_column='DEPT_TITLE', help_text='Borçlunun Adı Soyadı', max_length=150, null=True)),
            ],
            options={
                'db_table': 'SYS_BLACK_LIST',
            },
            bases=('appconfig.basemodel',),
        ),
        migrations.CreateModel(
            name='VergiBorcuListesi',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appconfig.basemodel')),
                ('borc_sahibi', models.CharField(db_column='DEPT_TITLE', help_text='Borçlunun Adı Soyadı', max_length=150, null=True)),
                ('vergi_departmani', models.CharField(db_column='TAX_DEPT', help_text='Vergi Departmanı', max_length=200, verbose_name='TAX DEPARTMENT')),
                ('kimlikno', models.CharField(db_column='TAXPAYER_NUMBER', help_text='Sahis firmasi ise TCKNO, Tuzel Kisilik iseVergi No', max_length=15)),
                ('esas_faaliyet_konusu', models.CharField(db_column='REAL_OPERATING_INCOME', help_text='Esas Faaliyet Konusu', max_length=500)),
                ('borc_miktari', models.FloatField(db_column='DEPT_AMOUNT', help_text='Borç Miktarı')),
            ],
            options={
                'db_table': 'TAX_DEBTS',
            },
            bases=('appconfig.basemodel',),
        ),
        migrations.CreateModel(
            name='Subtypes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appconfig.basemodel')),
                ('point', models.FloatField(db_column='PTS', help_text='Point of specified intervals of your subtype related Domain', max_length=100)),
                ('min_interval', models.FloatField(db_column='MIN_INTERVAL', help_text='Minimum interval', max_length=100)),
                ('max_interval', models.FloatField(blank=True, db_column='MAX_INTERVAL', help_text='Maximum interval', max_length=100, null=True)),
                ('domain', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='appconfig.domains')),
            ],
            options={
                'db_table': 'SUBTYPES',
            },
            bases=('appconfig.basemodel',),
        ),
    ]
