# Generated by Django 3.1.5 on 2021-01-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkaccount',
            name='firm_type',
            field=models.CharField(choices=[('Tüzel Kişilik', 'TUZEL_KISILIK'), ('Şahıs İşletmesi', 'SAHIS_ISLETMESI')], db_column='FIRM_TYPE', default='t', help_text='Business type of the firm', max_length=50, null=True, verbose_name='FIRM TYPE'),
        ),
    ]
