# Generated by Django 3.1.5 on 2021-01-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkaccount',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum yeri'),
        ),
        migrations.AlterField(
            model_name='checkaccount',
            name='city',
            field=models.CharField(max_length=70, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='checkaccount',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='checkaccount',
            name='firm_key_contact_personnel',
            field=models.CharField(max_length=70, null=True, verbose_name='Firma İletişim'),
        ),
        migrations.AlterField(
            model_name='checkaccount',
            name='sector',
            field=models.CharField(max_length=70, null=True, verbose_name='Sektör'),
        ),
    ]
