# Generated by Django 3.1.5 on 2021-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkaccount', '0003_auto_20210124_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkaccount',
            name='taxpayer_number',
            field=models.PositiveBigIntegerField(db_column='TAXPAYER_NUMBER', help_text='Sahis firmasi ise TCKNO, Tuzel Kisilik ise Vergi No', null=True, verbose_name='Kimlik No'),
        ),
    ]
