# Generated by Django 3.1.5 on 2021-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkaccount', '0004_auto_20210214_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkaccount',
            name='taxpayer_number',
            field=models.CharField(db_column='TAXPAYER_NUMBER', help_text='Sahis firmasi ise TCKNO, Tuzel Kisilik ise Vergi No', max_length=15, null=True, verbose_name='Kimlik No'),
        ),
    ]
